### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by viktorfreiman** [PatzEdi/Stockstir#2]
Hi, cool lib. I got this error when trying to install it. You need to set pyproject.toml correct.

~~~powershell
PS C:\Users\Viktor> docker run -it python bash
root@1164d78e93ab:/# pip install Stockstir
Collecting Stockstir
  Obtaining dependency information for Stockstir from https://files.pythonhosted.org/packages/b6/70/2de1a75b5eb85bf08d1cd8dcf8f7be92ee00af0250faab6d7fc7c3361853/stockstir-1.0.3-py3-none-any.whl.metadata
  Downloading stockstir-1.0.3-py3-none-any.whl.metadata (6.8 kB)
Downloading stockstir-1.0.3-py3-none-any.whl (7.3 kB)
Installing collected packages: Stockstir
Successfully installed Stockstir-1.0.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
root@1164d78e93ab:/# python
Python 3.11.5 (main, Sep  7 2023, 12:36:05) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Stockstir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/Stockstir/__init__.py", line 3, in <module>
    from .stockstir import gatherInfo
  File "/usr/local/lib/python3.11/site-packages/Stockstir/stockstir.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
~~~

I installed requests and then it worked.

**Comment by PatzEdi** [comment]
Hello! Oh, you are right, I forgot to link the requirements.txt to the pyproject.toml. Will do so in the next version (to be released either today or Saturday), sorry about that! I will keep this thread open until the next version releases. Thank you for trying out Stockstir and for helping this project out.

**Comment by PatzEdi** [comment]
V2 Has released and the problem is solved! :)
